### ISSUE TITLE
big data save fail

### ISSUE THREAD

**Issue by Jasonzhangjs** [MikaelEliasson/EntityFramework.Utilities#125]
When I batch insert 10,000 pieces of data, Object has 40 fields. I got an error : {"Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."}   
![image](https://user-images.githubusercontent.com/7445375/61864197-928d3080-af03-11e9-8e33-b4543c1be50c.png)

**Comment by RudeySH** [comment]
`InsertAll` allows you to specify `batchSize`, you could try making it smaller to see if it prevents hitting the timeout.

If you'd rather specify a larger timeout, I am maintaining a fork of EFUtilities that adds a configurable timeout to `InsertAll`:

https://github.com/RudeySH/EntityFramework.Utilities

NuGet package available over here: https://www.nuget.org/packages/RudeySH.EFUtilities/
