### ISSUE TITLE
Problem when using wrapped connections

### ISSUE THREAD

**Issue by MikaelEliasson** [MikaelEliasson/EntityFramework.Utilities#13]
Because it relies on the connection type to determine the provider it fails once a connection is wrapped with for example a profiler as NHProf.

See discussion https://twitter.com/andregauci/status/502478988246523904

Possible fix: Instead of type checking the connection check the provider part of the connection string in `context.Connection.ConnectionString`

**Comment by tsu1980** [comment]
Hi. I need `connection` parameter to Delete(), Update() methods too. Please consider it.
