### ISSUE TITLE
Does this project supports sqlite and mysql or any other sql engines?

### ISSUE THREAD

**Issue by Sellec** [MikaelEliasson/EntityFramework.Utilities#131]
Subj.

**Comment by RudeySH** [comment]
No, EFUtilities implements most of it's features by utilizing SqlBulkInsert, which is a SQL Server API. Some other features are implemented by rewriting SQL queries, but these queries will most likely not work on anything other than SQL Server. If I remember correctly, the code is set up so you can easily add different implementations for other DB systems, but the implementations themselves aren't there yet.

**Comment by MikaelEliasson** [comment]
Correct, it's possible to make it support those but not something that will be generally.
