### ISSUE TITLE
Document transaction support

### ISSUE THREAD

**Issue by MikaelEliasson** [MikaelEliasson/EntityFramework.Utilities#26]
The current batch operation DOES support transactions by using TransactionScope. Document this.

**Comment by dahrnsbrak** [comment]
Can you give a brief explanation of this?  I've done context.Database.BeginTransaction around my call to InsertAll, but it doesn't seem to work.

**Comment by MikaelEliasson** [comment]
Check this code.From one of my projects.

![image](https://cloud.githubusercontent.com/assets/888296/6887524/4badcbd0-d662-11e4-8339-9134e0196d9c.png)

**Comment by MikaelEliasson** [comment]
A bit more code than you need and `DB.Use`  is a replacement for `using(var db = new DbContext())`

**Comment by MikaelEliasson** [comment]
Fixed

**Comment by Gabriel-Espinoza** [comment]
Please leave more documentation about this. It's really unusable.

**Comment by thetalkingtree** [comment]
Just use 
  using (var ts = new TransactionScope())
            {
                using (DbEntities ctx = new DbEntities())
                {
                         EFBatchOperation.For(ctx, ctx.YourEntity).InsertAll(list);
                          ctx.SaveChanges();
                }
            ts.Complete();
          }
