### ISSUE TITLE
EF6 Database First approach support

### ISSUE THREAD

**Issue by aidforwork** [MikaelEliasson/EntityFramework.Utilities#27]
I'm sorry, but there is no word about DB First in docs. I tried to save an entity and had received NotSupportedException:

	var list = new List<MyEntity> { entity };
	EFBatchOperation.For(context, context.MyEntities).InsertAll(list);
	
When I use native EF code, everything is OK:
	
	context.MyEntities.Add(entity);
	context.SaveChanges();

Exception details here:

Message:
Creating a DbModelBuilder or writing the EDMX from a DbContext created using Database First or Model First is not supported. EDMX can only be obtained from a Code First DbContext created without using an existing DbCompiledModel.

StackTrace:
       at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer)
       at EntityFramework.Utilities.EfMapping.GetEdmx(DbContext db)
       at EntityFramework.Utilities.EfMapping..ctor(DbContext db)
       at EntityFramework.Utilities.EfMappingFactory.GetMappingsForContext(DbContext context)
       at EntityFramework.Utilities.EFBatchOperation`2.InsertAll(IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)

Is DB First supported? Thanks!

**UPD: EF 6.1.1 is used**

**Comment by MikaelEliasson** [comment]
Thank you for the report!

I will look into if I can get the metadata with DB first. Then it should be possible to add that support.

**Comment by MikaelEliasson** [comment]
For anyone else looking at this the edmx is used to get the mappings between db and application code. I know EF6.1 support better ways to get the mapping API but Utilities support 6.0 and up.

So I would need to get this data for 6.0. The related code is in https://github.com/MikaelEliasson/EntityFramework.Utilities/blob/master/EntityFramework.Utilities/EntityFramework.Utilities/MappingHelper.cs

**Comment by ErikEJ** [comment]
Why not drop support for 6.0 then?

**Comment by MikaelEliasson** [comment]
That's not a bad idea. I could make a release for some of the small fixes I have in the issues. Then upgrade to 6.1 and release 1.0. 

If they have 6.0 upgrading to newer 6.* should be easy.

**Comment by aidforwork** [comment]
Thank you for the reply!

It's true, the initial post is about EF 6.1.1, so I've added version number to it.

**Comment by MikaelEliasson** [comment]
Working on this one for next release. Looks like I have it solved

**Comment by MikaelEliasson** [comment]
Verified it's working. Release comming today.

**Comment by ajithk444** [comment]
Hey Mike. So does this mean the model first approach is supported from the release you will do today ?

**Comment by MikaelEliasson** [comment]
@aidforwork Yes, it should work. I have tested it, but only with a quite simple model. It will require EF 6.1.0 or higher though as the metadata apis wasn't available before that..

**Comment by MikaelEliasson** [comment]
new release is out. Depends on EF 6.1.3
