### ISSUE TITLE
IncludeEFU : An unhandled exception of type 'System.ArgumentException' occurred in EntityFramework.Utilities.dll

### ISSUE THREAD

**Issue by Tiku123** [MikaelEliasson/EntityFramework.Utilities#29]
Hello !
I'm using VB.net and entity framework 6.1
I try to use the IncludeEFU.
This is the Code :

Dim MyList as IeNumerable(Of  Article)
MyList= context.Articles.IncludeEFU(context, Function(t2) t2.F1_item).ToList

But I'm getting this error :
An unhandled exception of type 'System.ArgumentException' occurred in EntityFramework.Utilities.dll

Additional information: Could not find a MemberExpression

( note that  the standart .Include() command works correctly ).

What can I do ?
Thank you !

**Comment by RichardD2** [comment]
Does your lambda expression include a call to `Where`, `OrderBy`, or `OrderByDescending`, or is it just a property access call?

It looks like there's a difference between how lambda expressions are generated in C# and VB.NET when the expression calls extension methods on the property. VB is inserting an extra "Convert" `UnaryExpression` around the `PropertyExpression`, which causes the `SetCollectionModifiersAndGetChildProperty` method to fail to find the property.

For example, in C#:

    x => x.Property.Where(...)

produces a lambda expression where the body is a `MethodCallExpression` whose first argument is a `PropertyExpression`.

In VB.NET:

    Function (x) x.Property.Where(...)

produces a lambda expression where the body is a `MethodCallExpression` whose first argument is *a `UnaryExpression` whose operand is* a `PropertyExpression`. (Essentially `x => Convert(x.Property).Where(...)`).

A simplistic solution would be to add an extra loop in the `SetCollectionModifiersAndGetChildProperty` method:

    while (temp is MethodCallExpression)
    {
        ...
    }
    while (temp is UnaryExpression)
    {
        var ue = temp as UnaryExpression;
        temp = ue.Operand;
    }

**Comment by Tiku123** [comment]
My call I just :
context.Articles.IncludeEFU(context, Function(t2) t2.F1_item).ToList
I doesn't try to use order by or .. the others ,because even thiis produce an error

**Comment by MikaelEliasson** [comment]
Great find @RichardD2. Didn't know there was a difference.

@Tiku123 F1_Item has to be a collection for IncludeEFU to work.

It's very limited because the code to make it work is actually quite complex. I'm thinking about adding some more manual methods to do the relationship fixup to handle more complex cases.

**Comment by Tiku123** [comment]
Hello !
F1_Item is a collection.
Actually , the same code that I wrote , works on a C# project , but I want to use it on a vb.net project. Is there any hope for a quick solution ?
Thank you !

**Comment by MikaelEliasson** [comment]
Should be fixed now
