### ISSUE TITLE
Odd error

### ISSUE THREAD

**Issue by jonpanky** [MikaelEliasson/EntityFramework.Utilities#31]
Hi Mikael, 

I'm getting this error:

Creating a DbModelBuilder or writing the EDMX from a DbContext created using Database First or Model First is not supported. EDMX can only be obtained from a Code First DbContext created without using an existing DbCompiledModel.

when using :

                foreach (var pr in products)
                {
                    list.Add(new tblGoogleProduct
                        {
                            DateTimeInsertGoogle = DateTime.Now,
                            DateTimeUpdate = DateTime.Now,
                            IsForUpdate = true,
                            IsOnGoogle = true,
                            PictureId = pr.PictureId
                        });
                }

                EFBatchOperation.For(db, db.tblGoogleProducts).InsertAll(list);

Any pointers on this?

Cheers
Jon

**Comment by MikaelEliasson** [comment]
Hi! Might this be the same issue as #27  ?

**Comment by jonpanky** [comment]
Hi mikael I'll try that

**Comment by MikaelEliasson** [comment]
Duplicate. of #27. Closing this
