### ISSUE TITLE
Error generating Update Query for multicolumn Primary Key

### ISSUE THREAD

**Issue by hanpera** [MikaelEliasson/EntityFramework.Utilities#46]
The Method UpdateAll on  Table that have 2 columns Primary Key has generated a query like this:

UPDATE [StudyAssumption]
                SET
                    [IsSponsor] = TEMP.[IsSponsor],[IsCromsource] = TEMP.[IsCromsource]
                FROM
                    [StudyAssumption] ORIG
                INNER JOIN
                     [temp_StudyAssumption_635693559224566926] TEMP
                ON 
                    ORIG.[IdStudy] = TEMP.[IdStudy], ORIG.[IdAssumptionType] = TEMP.[IdAssumptionType]

There is a "," instead an "AND in the ON Clause that results in a SQL Server error

**Comment by MikaelEliasson** [comment]
Fixed an released in 1.0.1

**Comment by MikaelEliasson** [comment]
Thank you for noticing this. Please tell me if the new version didn't fix the problem.
