### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ewassef** [MikaelEliasson/EntityFramework.Utilities#88]
@MikaelEliasson  are you still maintaining this repo? I would be more than happy to help if you would like

**Comment by abatishchev** [comment]
@MikaelEliasson bump

**Comment by RudeySH** [comment]
As of today I have decided to maintain a fork of this project. See https://github.com/RudeySH/EntityFramework.Utilities

**Comment by abatishchev** [comment]
Cool, way to go!

**Comment by abatishchev** [comment]
However I don't see issues in that repo. Do you want to use this repobfor issue? Not sure that will work well.
Nuget package. What would be the name? I'd use EFUtilities2.
Folder structure. I'd refactor it to src, tests, like any other modern project. Move the license file to the root.
CI/CD. I'd use AppVeyor. I can help.
Branch policies/PR review. Should be enabled for master. I also can help.

**Comment by RudeySH** [comment]
@abatishchev I didn't realize issues are disabled by default in forks, I have enabled it.
I will be publishing a NuGet package soon, I haven't decided on the name yet. EFUtilities2 sounds good although I don't want users to think there are breaking changes.
I won't be making big changes to the folder structure anytime soon. That would make merging new pull requests on this repository difficult.
I haven't given the other stuff much thought yet.
